let st_generateBtn = document.querySelector("#generate");
let st_password = document.querySelector("#password");
let st_alphanum = document.querySelector("#alphanum");
let st_funk = document.querySelector("#funky");
let st_word = document.querySelector("#word");
let st_pwLength = document.querySelector("#pwLength");
let st_pwLenInd = document.querySelector("#pwLenInd");


// Password object to hold the password value, length and if the user wanted to include funky characters.
let password = {

  value: "",
  length: 8,
  criteria: [true, false, false],
  //criteria[0] = alphanumeric
  //criteria[1] = funky
  //criteria[2] = word-by-word

}

//User Input: Criteria
st_alphanum.checked = password.criteria[0]; // Set Alphanumeric as default.
// console.log(password.criteria[0]);

//User Input: Password length
st_pwLength.value = password.length;
st_pwLenInd.innerHTML = st_pwLength.value; //Prints default password length to page.
st_pwLength.addEventListener("change", setPwLength); // Change the printed password length

function setPwLength() {

  st_pwLenInd.innerHTML = st_pwLength.value;

}

// Create arrays for usable characters: alphanumeric array, funky character array

const alphaLower = [
  "a", "b", "c", "d", "e", "f", "g", "h",
  "i", "j", "k", "l", "m", "n", "o", "p",
  "q", "r", "s", "t", "u", "v", "w", "x",
  "y", "z"
];

const alphaUpper = [
  "A", "B", "C", "D", "E", "F", "G", "H",
  "I", "J", "K", "L", "M", "N", "O", "P",
  "Q", "R", "S", "T", "U", "V", "W", "X",
  "Y", "Z"
];

const numeric = [
  "1", "2", "3", "4", "5", "6", "7", "8",
  "9"
]

const funky = [
  "`", "!", "@", "#", "$", "%", "^", "&",
  "*", "(", ")", "_", "+", "~", "-", "=",
  "[", "]", ";", "'", ",", ".", "/", "{",
  "}", "|", ":", '"', "<", ">", "?"
];

const wordy = [

  "deep", ""

]

// Taken from www.bestwordlist.com
let unformattedString = "AAHING AALIIS AARRGH AARTIS ABACAS ABACUS ABAKAS ABAMPS ABANDS ABASED ABASER ABASES ABASIA ABATED ABATER ABATES ABATIS ABATOR ABATTU ABAYAS ABBACY ABBESS ABBEYS ABBOTS ABCEES ABDABS ABDUCE ABDUCT ABEARS ABEIGH ABELES ABELIA ABHORS ABIDED ABIDER ABIDES ABJECT ABJURE ABLATE ABLAUT ABLAZE ABLEST ABLETS ABLING ABLINS ABLOOM ABLUSH ABMHOS ABOARD ABODED ABODES ABOHMS ABOLLA ABOMAS ABORAL ABORDS ABORNE ABORTS ABOUND ABOUTS ABOVES ABRADE ABRAID ABRAYS ABRAZO ABREGE ABRINS ABROAD ABRUPT ABSEIL ABSENT ABSEYS ABSITS ABSORB ABSURD ABULIA ABULIC ABUNAS ABURST ABUSED ABUSER ABUSES ABVOLT ABWATT ABYING ABYSMS ACACIA ACAJOU ACANTH ACARID ACARUS ACATER ACATES ACCEDE ACCEND ACCENT ACCEPT ACCESS ACCITE ACCLOY ACCOIL ACCORD ACCOST ACCOYS ACCREW ACCRUE ACCUSE ACEDIA ACETAL ACETIC ACETIN ACETUM ACETYL ACHAGE ACHENE ACHIER ACHING ACHKAN ACIDER ACIDIC ACIDLY ACINAR ACINIC ACINUS ACKEES ACKERS ACKNEW ACKNOW ACMITE ACNODE ACORNS ACQUIT ACRAWL ACROSS ACTANT ACTING ACTINS ACTION ACTIVE ACTONS ACTORS ACTUAL ACTURE ACUATE ACUITY ACULEI ACUMEN ACUTER ACUTES ADAGES ADAGIO ADAPTS ADAWED ADDEEM ADDEND ADDERS ADDICT ADDIES ADDING ADDIOS ADDLED ADDLES ADDOOM ADDUCE ADDUCT ADEEMS ADENYL ADEPTS ADHANS ADHERE ADIEUS ADIEUX ADIPIC ADJIGO ADJOIN ADJURE ADJUST ADLAND ADMASS ADMINS ADMIRE ADMITS ADMIXT ADNATE ADNEXA ADNOUN ADOBES ADOBOS ADONIS ADOORS ADOPTS ADORED ADORER ADORES ADORNS ADREAD ADRIFT ADROIT ADSORB ADSUKI ADUKIS ADULTS ADUSTS ADVECT ADVENE ADVENT ADVERB ADVERT ADVEWS ADVICE ADVISE ADWARD ADWARE ADYTUM ADZING ADZUKI AECIAL AECIUM AEDILE AEDINE AEFALD AEMULE AENEUS AEONIC AERATE AERIAL AERIED AERIER AERIES AERIFY AERILY AEROBE AERUGO AESCES AETHER AFARAS AFAWLD AFEARD AFEARS AFFAIR AFFEAR AFFECT AFFEER AFFIED AFFIES AFFINE AFFIRM AFFLUX AFFORD AFFRAP AFFRAY AFFRET AFFYDE AFGHAN AFIELD AFLAME AFLOAT AFRAID AFREET AFRESH AFRITS AFRONT AFTERS AFTOSA AGAMAS AGAMIC AGAMID AGAMIS AGAPAE AGAPAI AGAPES AGARIC AGATES AGAVES AGAZED AGEDLY AGEING AGEISM AGEIST AGENCY AGENDA AGENES AGENTS AGGADA AGGERS AGGIES AGGROS AGHAST AGILAS AGILER AGINGS AGISMS AGISTS AGITAS AGLARE AGLEAM AGLETS AGLOOS AGNAIL AGNAME AGNATE AGNISE AGNIZE AGOGES AGOGIC AGOING AGONAL AGONES AGONIC AGORAE AGORAS AGOROT AGOUTA AGOUTI AGOUTY AGRAFE AGREED AGREES AGREGE AGRIAS AGRISE AGRIZE AGRYZE AGUISE AGUISH AGUIZE AGUTIS AHCHOO AHIMSA AHOLDS AHORSE AIDANT AIDERS AIDFUL AIDING AIDMAN AIDMEN AIGLET AIGRET AIKIDO AIKONA AILING AIMERS AIMFUL AIMING AINGAS AIOLIS AIRBAG AIRBUS AIRERS AIREST AIRGAP AIRIER AIRILY AIRING AIRMAN AIRMEN AIRNED AIRTED AIRTHS AIRWAY AISLED AISLES AIVERS AIZLES AJIVAS AJOWAN AJUGAS AJWANS AKATEA AKEAKE AKEDAH AKELAS AKENES AKHARA AKIMBO AKITAS ALAAPS ALALIA ALAMOS ALANDS ALANGS ALANIN ALANTS ALANYL ALAPAS ALARMS ALARUM ALASKA ALATED ALATES ALAYED ALBATA ALBEDO ALBEIT ALBERT ALBINO ALBITE ALBUGO ALBUMS ALCADE ALCAIC ALCIDS ALCOOL ALCOVE ALDEAS ALDERN ALDERS ALDOLS ALDOSE ALDRIN ALECKS ALEGAR ALEGGE ALEPHS ALERCE ALERTS ALEVIN ALEXIA ALEXIC ALEXIN ALEYED ALEYES ALFAKI ALGATE ALGINS ALGOID ALGORS ALGUMS ALIBIS ALIBLE ALIDAD ALIENS ALIGHT ALIGNS ALINED ALINER ALINES ALIPED ALISMA ALISON ALIYAH ALIYAS ALIYOS ALIYOT ALKALI ALKANE ALKENE ALKIES ALKINE ALKOXY ALKYDS ALKYLS ALKYNE ALLAYS ALLEES ALLEGE ALLELE ALLELS ALLEYS ALLICE ALLIED ALLIES ALLIUM ALLODS ALLONS ALLOTS ALLOWS ALLOYS ALLUDE ALLURE ALLYLS ALLYOU ALMAHS ALMAIN ALMEHS ALMERY ALMNER ALMOND ALMOST ALMOUS ALMUCE ALMUDE ALMUDS ALMUGS ALNAGE ALNICO ALODIA ALOGIA ALOHAS ALOINS ALPACA ALPEEN ALPHAS ALPHYL ALPINE ALSIKE ALSOON ALTARS ALTERN ALTERS ALTEZA ALTHEA ALUDEL ALULAE ALULAR ALUMIN ALUMNA ALUMNI ALURES ALVINE ALWAYS AMADOU AMARNA AMATED AMATES AMATOL AMAUTS AMAZED AMAZES AMAZON AMBACH AMBAGE AMBANS AMBARI AMBARY AMBEER AMBERS AMBERY AMBITS AMBLED AMBLER AMBLES AMBUSH AMEBAE AMEBAN AMEBAS AMEBIC AMEERS AMELIA AMENDE AMENDS AMENED AMENTA AMENTS AMERCE AMICES AMICUS AMIDES AMIDIC AMIDIN AMIDOL AMIDST AMIGAS AMIGOS AMINES AMINIC AMISES AMMANS AMMINE AMMINO AMMONO AMMONS AMNION AMNIOS AMOEBA AMOLES AMOMUM AMOOVE AMORAL AMORCE AMORET AMOUNT AMOURS AMOVED AMOVES AMOWTS AMPERE AMPING AMPLER AMPULE AMPULS AMRITA AMRITS AMTMAN AMTRAC AMUCKS AMULET AMUSED AMUSER AMUSES AMUSIA AMYLIC AMYLUM AMYTAL ANABAS ANADEM ANALLY ANALOG ANANAS ANANKE ANARCH ANATAS ANATTA ANATTO ANBURY ANCHOR ANCHOS ANCILE ANCLES ANCOME ANCONE ANCORA ANDROS ANEARS ANEATH ANELED ANELES ANEMIA ANEMIC ANENST ANERGY ANERLY ANETIC ANGARY ANGELS ANGERS ANGICO ANGINA ANGLED ANGLER ANGLES ANGLOS ANGOLA ANGORA ANGSTS ANGSTY ANICCA ANICUT ANIGHT ANILIN ANIMAL ANIMAS ANIMES ANIMIS ANIMUS ANIONS ANISES ANISIC ANKERS ANKLED ANKLES ANKLET ANKUSH ANLACE ANLAGE ANNALS ANNATS ANNEAL ANNEXE ANNONA ANNOYS ANNUAL ANNULI ANNULS ANODAL ANODES ANODIC ANOINT ANOLES ANOMIC ANOMIE ANONYM ANOPIA ANORAK ANOUGH ANOXIA ANOXIC ANSATE ANSWER ANTARA ANTARS ANTEED ANTHEM ANTHER ANTIAR ANTICK ANTICS ANTING ANTLER ANTLIA ANTRAL ANTRES ANTRUM ANURAL ANURAN ANURIA ANURIC ANUSES ANVILS ANYHOW ANYONE ANYONS ANYWAY AORIST AORTAE AORTAL AORTAS AORTIC AOUDAD APACHE APATHY APEDOM APEMAN APEMEN BONNES BONNET BONNIE BONOBO BONSAI BONXIE BONZER BONZES BOOBED BOOBIE BOOBOO BOOCOO BOODIE BOODLE BOOGER BOOGEY BOOGIE BOOHAI BOOHED BOOHOO BOOING BOOJUM BOOKED BOOKER BOOKIE BOOKOO BOOKSY BOOLED BOOMED BOOMER BOONER BOONGA BOONGS BOORDE BOORDS BOORKA BOOSED BOOSES BOOSTS BOOTED BOOTEE BOOTHS BOOTIE BOOZED BOOZER BOOZES BOOZEY BOPEEP BOPPED BOPPER BORAGE BORAKS BORALS BORANE BORATE BORDAR BORDEL BORDER BORDES BOREAL BOREAS BOREEN BOREES BORERS BORGOS BORIDE BORING BORKED BORMED BORNYL BORONS BORREL BORROW BORSCH BORSHT BORSIC BORZOI BOSBOK BOSCHE BOSHES BOSHTA BOSKER BOSKET BOSOMS BOSOMY BOSONS BOSQUE BOSSED BOSSER BOSSES BOSSET BOSTON BOSUNS BOTANY BOTCHY BOTELS BOTFLY BOTHAN BOTHER BOTHIE BOTNET BOTONE BOTTED BOTTES BOTTLE BOTTOM BOUBOU BOUCHE BOUCLE BOUDIN BOUFFE BOUGED BOUGES BOUGET BOUGHS BOUGHT BOUGIE BOULES BOULLE BOULTS BOUNCE BOUNCY BOUNDS BOUNED BOUNTY BOURDS BOURGS BOURNE BOURNS BOURSE BOUSED BOUSES BOUTON BOVATE BOVIDS BOVINE BOVVER BOWATS BOWELS BOWERS BOWERY BOWETS BOWFIN BOWGET BOWING BOWLED BOWLEG BOWLER BOWMAN BOWMEN BOWNED BOWNES BOWPOT BOWSAW BOWSED BOWSER BOWSES BOWSEY BOWSIE BOWWOW BOWYER BOXCAR BOXERS BOXFUL BOXIER BOXILY BOXING BOYARD BOYARS BOYAUX BOYING BOYISH BOYLAS BRAAIS BRAATA BRACED BRACER BRACES BRACHS BRACKS BRACTS BRAGGY BRAGLY BRAHMA BRAIDE BRAIDS BRAILS BRAINS BRAINY BRAIRD BRAISE BRAIZE BRAKED BRAKES BRAMES BRANCH BRANDS BRANDY BRANKS BRANKY BRANLE BRANNY BRANTS BRASCO BRASES BRASHY BRASIL BRASSY BRASTS BRATTY BRAVAS BRAVED BRAVER BRAVES BRAVOS BRAWER BRAWLS BRAWLY BRAWNS BRAWNY BRAYED BRAYER BRAZAS BRAZED BRAZEN BRAZER BRAZES BRAZIL BREACH BREADS BREADY BREAKS BREAMS BREARE BREAST BREATH BREDED BREDES BREDIE BREECH BREEDS BREEKS BREERS BREESE BREEST BREEZE BREEZY BREGMA BREHON BREIDS BREIST BREKKY BRENNE BRENTS BRERES BRETON BREVES BREVET BREVIS BREWED BREWER BREWIS BREYED BRIARD BRIARS BRIARY BRIBED BRIBEE BRIBER BRIBES BRICHT BRICKS BRICKY BRIDAL BRIDED BRIDES BRIDGE BRIDIE BRIDLE BRIEFS BRIERS BRIERY BRIGHT BRIGUE BRILLO BRILLS BRINED BRINER BRINES BRINGS BRINKS BRINNY BRIONY BRISES BRISKS BRISKY BRITHS BRITTS BRIZES BROACH BROADS BROCHE BROCHO BROCHS BROCKS BROGAN BROGHS BROGUE BROILS BROKED BROKEN BROKER BROKES BROLGA BROLLY BROMAL BROMES BROMIC BROMID BROMIN BROMOS BRONCO BRONCS BRONDS BRONZE BRONZY BROOCH BROODS BROODY BROOKS BROOLS BROOMS BROOMY BROOSE BROSES BROTHS BROTHY BROUGH BROUZE BROWED BROWNS BROWNY BROWSE BROWST BROWSY BRUCIN BRUGHS BRUINS BRUISE BRUITS BRULES BRULOT BRUMAL BRUMBY BRUMES BRUNCH BRUNET BRUNTS BRUSHY BRUSTS BRUTAL BRUTED BRUTER BRUTES BRUXED BRUXES BRYONY BUAZES BUBALE BUBALS BUBBAS BUBBLE BUBBLY BUBKES BUBOED BUBOES BUCCAL BUCHUS BUCKED BUCKER BUCKET BUCKIE BUCKLE BUCKOS BUCKRA BUCKUS BUDDED BUDDER BUDDHA BUDDLE BUDGED BUDGER BUDGES BUDGET BUDGIE BUFFED BUFFEL BUFFER BUFFET BUFFOS BUGEYE BUGGAN BUGGED BUGGER BUGGIN BUGLED BUGLER BUGLES BUGLET BUGONG BUGOUT BUGSHA BUHUND BUIBUI BUILDS BUISTS BUKSHI BULBAR BULBED BULBEL BULBIL BULBUL BULGED BULGER BULGES BULGUR BULIMY BULKED BULKER BULLAE BULLED BULLER BULLET BULSES BUMALO BUMBAG BUMBLE BUMBOS BUMKIN BUMMED BUMMEL BUMMER BUMMLE BUMPED BUMPER BUMPHS BUNCED BUNCES BUNCHY BUNCOS BUNDED BUNDHS BUNDLE BUNDTS BUNDUS BUNGED BUNGEE BUNGER BUNGEY BUNGIE BUNGLE BUNIAS BUNION BUNJEE BUNJES BUNJIE BUNKED BUNKER BUNKOS BUNKUM BUNNET BUNNIA BUNSEN BUNTAL BUNTED BUNTER BUNYAS BUNYIP BUOYED BUPKES BUPKUS BUPPIE BUQSHA BURANS BURBLE BURBLY BURBOT BURDEN BURDIE BUREAU BURETS BURGEE BURGER BURGHS BURGLE BURGOO BURHEL BURIAL BURIED BURIER BURIES BURINS BURITI BURKAS BURKED BURKER BURKES BURLAP BURLED BURLER BURLEY BURNED BURNER BURNET BURNIE BUROOS BURPED BURPEE BURQAS BURRED BURREL BURRER BURROS BURROW BURSAE BURSAL BURSAR BURSAS BURSES BURSTS BURTON BUSBAR BUSBOY BUSERA BUSHED BUSHEL BUSHER BUSHES BUSHIE BUSHWA BUSIED BUSIER BUSIES BUSILY BUSING BUSKED BUSKER BUSKET BUSKIN BUSMAN BUSMEN BUSSED BUSSES BUSSUS BUSTED BUSTEE BUSTER BUSTIC BUSTIS BUSTLE BUTANE BUTENE BUTEOS BUTLED BUTLER BUTLES BUTTED BUTTER BUTTES BUTTLE BUTTON BUTUTS BUTYLS BUYERS BUYING BUYOFF BUYOUT BUZUKI BUZZED BUZZER BUZZES BWANAS BWAZIS BYDING BYELAW BYGONE BYKING BYLANE BYLAWS BYLINE BYLIVE BYNAME BYPASS BYPAST BYPATH BYPLAY BYRLAW BYRLED BYRNIE BYROAD BYROOM BYSSAL BYSSUS BYTALK BYWAYS BYWORD BYWORK BYZANT CAAING CABALA CABALS CABANA CABBED CABBIE CABERS CABINS CABLED CABLER CABLES CABLET CABMAN CABMEN CABOBS CABOCS CABRIE CABRIO CABRIT CACAOS CACHED CACHES CACHET CACHOU CACKLE CACOON CACTUS CADAGA CADAGI CADDIE CADDIS CADEAU CADEES CADENT CADETS CADGED CADGER CADGES CADIES CADMIC CADRES CADUAC CAECAL CAECUM CAEOMA CAESAR CAFARD CAFILA CAFTAN CAGERS CAGIER CAGILY CAGING CAGMAG CAGOTS CAGOUL CAHIER CAHOOT CAHOWS CAILLE CAIMAC CAIMAN CAIQUE CAIRDS CAIRNS CAIRNY CAJOLE CAKIER CAKING CALALU CALAMI CALASH CALCAR CALCED CALCES CALCIC CALEFY CALESA CALICO CALIFS CALIGO CALIMA CALIPH CALKED CALKER CALKIN CALLAN CALLAS CALLED CALLEE CALLER CALLET CALLID CALLOP CALLOW CALLUS CALMED CALMER CALMLY CALORY CALPAC CALPAS CALQUE CALTHA CALVED CALVER CALVES WENGES WERRIS WESAND WESKIT WESTED WESTER WESTIE WETHER WETTED WETTER WETTIE WEXING WEYARD WEZAND WHACKO WHACKS WHACKY WHALED WHALER WHALES WHALLY WHAMMO WHAMMY WHANAU WHANGS WHARES WHARFS WHARVE WHATAS WHATEN WHATNA WHATSO WHAUPS WHAURS WHEALS WHEARE WHEATS WHEATY WHEECH WHEELS WHEELY WHEENS WHEEPS WHEESH WHEEZE WHEEZY WHEFTS WHELKS WHELKY WHELMS WHELPS WHENAS WHENCE WHENUA WHENWE WHERES WHERRY WHERVE WHEUGH WHEWED WHEYEY WHIDAH WHIFFS WHIFFY WHIFTS WHILED WHILES WHILLY WHILOM WHILST WHIMMY WHIMSY WHINED WHINER WHINES WHINEY WHINGE WHINNY WHIPPY WHIRLS WHIRLY WHIRRS WHIRRY WHISHT WHISKS WHISKY WHISTS WHITED WHITEN WHITER WHITES WHITEY WHIZZY WHOLES WHOLLY WHOMPS WHOMSO WHOOFS WHOOPS WHOOSH WHOOTS WHORED WHORES WHORLS WHORTS WHOSIS WHUMPS WHYDAH WIBBLE WICCAN WICCAS WICHES WICKED WICKEN WICKER WICKET WICOPY WIDDER WIDDIE WIDDLE WIDELY WIDENS WIDEST WIDGET WIDGIE WIDISH WIDOWS WIDTHS WIELDS WIELDY WIENER WIENIE WIFELY WIFEYS WIFIES WIFING WIGANS WIGEON WIGGAS WIGGED WIGGER WIGGLE WIGGLY WIGHTS WIGLET WIGWAG WIGWAM WIKIUP WILDED WILDER WILDLY WILFUL WILGAS WILIER WILILY WILING WILJAS WILLED WILLER WILLET WILLEY WILLIE WILLOW WILTED WILTJA WIMBLE WIMMIN WIMPED WIMPLE WINCED WINCER WINCES WINCEY WINDAC WINDAS WINDED WINDER WINDLE WINDOW WINDUP WINERY WINGED WINGER WINGES WINIER WINING WINISH WINKED WINKER WINKLE WINNED WINNER WINNLE WINNOW WINOES WINSEY WINTER WINTLE WINTRY WINZES WIPERS WIPING WIPPEN WIRERS WIRIER WIRILY WIRING WIRRAH WISARD WISDOM WISELY WISENT WISEST WISHED WISHER WISHES WISING WISKET WISPED WISSED WISSES WISTED WISTLY WITANS WITCHY WITGAT WITHAL WITHED WITHER WITHES WITHIN WITING WITNEY WITTED WITTER WITTOL WIVERN WIVERS WIVING WIZARD WIZENS WIZIER WIZZEN WIZZES WOADED WOALDS WOBBLE WOBBLY WODGES WOEFUL WOGGLE WOLFED WOLFER WOLVED WOLVER WOLVES WOMANS WOMBAT WOMBED WOMERA WOMMIT WONDER WONGAS WONGIS WONING WONNED WONNER WONTED WONTON WOOBUT WOODED WOODEN WOODIE WOODSY WOOERS WOOFED WOOFER WOOING WOOLDS WOOLED WOOLEN WOOLER WOOLIE WOOLLY WOONED WOOPIE WOOSEL WOOSES WOPPED WORDED WORKED WORKER WORKUP WORLDS WORMED WORMER WORMIL WORRAL WORREL WORRIT WORSED WORSEN WORSER WORSES WORSET WORSTS WORTHS WORTHY WORTLE WOTTED WOUBIT WOULDS WOUNDS WOUNDY WOVENS WOWFER WOWING WOWSER WRACKS WRAITH WRANGS WRASSE WRASTS WRATHS WRATHY WRAWLS WRAXLE WREAKS WREATH WRECKS WRENCH WRESTS WRETCH WRETHE WRICKS WRIEST WRIGHT WRINGS WRISTS WRISTY WRITER WRITES WRITHE WROATH WROKEN WRONGS WROOTS WRYEST WRYING WUDDED WUKKAS WULLED WUNNER WURLEY WURLIE WURSTS WURZEL WUSHUS WUSSES WUTHER WUXIAS WUZZLE WYCHES WYLING WYTING WYVERN XEBECS XENIAL XENIAS XENIUM XENONS XEROMA XOANON XYLANS XYLEMS XYLENE XYLOID XYLOLS XYLOMA XYLOSE XYLYLS XYSTER XYSTOI XYSTOS XYSTUS YABBAS YABBER YABBIE YACCAS YACHTS YACKAS YACKED YACKER YAFFED YAFFLE YAGERS YAGGER YAHOOS YAIRDS YAKKAS YAKKED YAKKER YAKOWS YAKUZA YAMENS YAMMER YAMUNS YANKED YANKER YANKIE YANQUI YANTRA YAOURT YAPOCK YAPOKS YAPONS YAPPED YAPPER YAPPIE YAQONA YARCOS YARDED YARDER YARELY YAREST YARFAS YARKED YARNED YARNER YARPHA YARRAN YARROW YARTAS YARTOS YASMAK YATTER YAUPED YAUPER YAUPON YAUTIA YAWING YAWLED YAWNED YAWNER YAWPED YAWPER YBLENT YBOUND YBRENT YCLEPT YEALMS YEANED YEARDS YEARLY YEARNS YEASTS YEASTY YECCHS YEDING YEELIN YELLED YELLER YELLOW YELMED YELPED YELPER YEMMER YENNED YENTAS YENTES YEOMAN YEOMEN YERBAS YERDED YERKED YESKED YESSED YESSES YESTER YETTIE YEUKED YEVING YEXING YICKER YIDAKI YIELDS YIKING YIKKER YIPPED YIPPEE YIPPER YIPPIE YIRDED YIRKED YIRRED YIRTHS YITIES YITTEN YMPING YNAMBU YOBBOS YOCKED YODELS YODLED YODLER YODLES YOGEES YOGINI YOGINS YOGISM YOGURT YOICKS YOJANA YOJANS YOKELS YOKERS YOKING YOKKED YOLKED YOMPED YONDER YONKER YONNIE YOPPER YORKED YORKER YORKIE YORPED YOUKED YOUNGS YOUPON YOURTS YOUTHS YOUTHY YOWIES YOWING YOWLED YOWLER YOWLEY YPIGHT YPLAST YRNEHS YSHEND YSHENT YTTRIA YTTRIC YUCCAS YUCKED YUCKER YUKATA YUKIER YUKING YUKKED YULANS YUMPED YUMPIE YUNXES YUPONS YUPPIE YURTAS YUTZES YWROKE ZABETA ZABRAS ZADDIK ZAFFAR ZAFFER ZAFFIR ZAFFRE ZAFTIG ZAGGED ZAIKAI ZAIRES ZAKATS ZAMANG ZAMANS ZAMBOS ZAMBUK ZAMIAS ZANANA ZANDER ZANIED ZANIER ZANIES ZANILY ZANJAS ZANTES ZANZAS ZANZES ZAPATA ZAPPED ZAPPER ZARAPE ZAREBA ZARIBA ZARNEC ZAYINS ZAZENS ZEALOT ZEATIN ZEBECK ZEBECS ZEBRAS ZEBUBS ZECHIN ZELANT ZELOSO ZENANA ZENDIK ZENITH ZEPHYR ZERDAS ZEREBA ZERIBA ZEROED ZEROES ZEROTH ZESTED ZESTER ZEUGMA ZHOMOS ZIBETH ZIBETS ZIGANS ZIGGED ZIGZAG ZILLAH ZILLAS ZIMBIS ZIMMER ZINCED ZINCIC ZINCKY ZINCOS ZINEBS ZINGED ZINGEL ZINGER ZINKED ZINKES ZINNIA ZIPPED ZIPPER ZIPPOS ZIPTOP ZIRAMS ZIRCON ZITHER ZIZELS ZIZITH ZIZZED ZIZZES ZIZZLE ZLOTYS ZOAEAE ZOAEAS ZOARIA ZOCALO ZOCCOS ZODIAC ZOECIA ZOETIC ZOFTIG ZOISMS ZOISTS ZOMBIE ZOMBIS ZONARY ZONATE ZONDAS ZONERS ZONING ZONKED ZONOID ZONULA ZONULE ZONURE ZOOEAE ZOOEAL ZOOEAS ZOOIDS ZOOIER ZOOMED ZOONAL ZOONED ZOONIC ZOOZOO ZORILS ZORINO ZORROS ZOSTER ZOUAVE ZOUNDS ZOYSIA ZUFOLI ZUFOLO ZUPANS ZYDECO ZYGOID ZYGOMA ZYGOSE ZYGOTE ZYMASE ZYMITE ZYMOID ZYMOME ZYTHUM";

let wordArray = unformattedString.split(" ");

function generateArray(x, y, z) {

  let localBigArray = [];

  if (x) {

    localBigArray = alphaLower.concat(alphaUpper, numeric);

  } else if (y) {

    localBigArray = alphaLower.concat(alphaUpper, numeric, funky);

  } else if (z) {

    localBigArray = wordArray;

  }

  return localBigArray;

}

// Create function to create new randomized array of length given by user, include 0.
// Add functionality to check if there are funky characters in the password if the user has selected funky, if there are no funky characters, re-generate.

function randomNumber(bigArray) {

  let x = Math.floor(Math.random() * bigArray.length);

  return x;

}

function createRandomPassword(len, bigArray) {

  let passwordArray = [];
  let passwordString = "";

  if (password.criteria[2]) {

    for (let i = 0; i < len; i++) {

      passwordArray[i] = bigArray[randomNumber(bigArray)] + "-";

    }

    passwordString = passwordArray.join("");
    passwordString = passwordString.slice(0, passwordString.length - 1);

  } else {

    for (let i = 0; i < len; i++) {

      passwordArray[i] = bigArray[randomNumber(bigArray)];

    }

    passwordString = passwordArray.join(""); // Convert array to string

  }

  return passwordString;

}

// Send string to output 'passwordText.value'

// Write password to the #password output
function writePassword() {


  // Capture data
  password.length = st_pwLength.value; //Password length

  if (st_alphanum.checked) { // Alphanumeric

    password.criteria[0] = true;
    password.criteria[1] = false;
    password.criteria[2] = false;

  } else if (st_funk.checked) { // Funky

    password.criteria[0] = false;
    password.criteria[1] = true;
    password.criteria[2] = false;

  } else if (st_word.checked) { // Word-by-word

    password.criteria[0] = false;
    password.criteria[1] = false;
    password.criteria[2] = true;

  }

  const bigArray = generateArray(password.criteria[0], password.criteria[1], password.criteria[2]); // Generates array acording to the selected radio button

  password.value = createRandomPassword(password.length, bigArray);

  console.log(password.value);
  st_password.innerHTML = password.value;

}

// Add event listener to generate button
st_generateBtn.addEventListener("click", writePassword);